pipeline:
  name: First Build Pipeline
  identifier: First_Build_Pipeline
  projectIdentifier: goapppipelinedemoproject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: org.orglevelgithubconnector
        build: <+input>
  stages:
    - stage:
        name: Build Stage
        identifier: Build_Stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: GoInstallBuildTest
                  identifier: GoInstallBuildTest
                  spec:
                    shell: Sh
                    command: |-
                      echo "Harness CI is fast!"
                      echo "Build number:" <+pipeline.sequenceId>
                      echo "Project Name:" <+project.identifier>
    - stage:
        name: Stage 2
        identifier: Stage_2
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: run step one
                  identifier: run_step_one
                  spec:
                    shell: Sh
                    command: echi "Hello from step 1 in stage 2"
